### ISSUE TITLE
Error: Invalid status code: 1

### ISSUE THREAD

**Issue by GWen124** [TobKed/github-forks-sync-action#10]
Run TobKed/github-forks-sync-action@master
  with:
    github_token: ***
    upstream_repository: jerrykuku/luci-theme-argon
    upstream_branch: 18.06
    target_repository: GWen124/luci-theme-argon
    target_branch: 18.06
    force: false
    tags: false
Started: bash /home/runner/work/_actions/TobKed/github-forks-sync-action/master/start.sh
Synchronizing repostiory GWen124/luci-theme-argon:18.06 with jerrykuku/luci-theme-argon:18.06
Cloning into 'luci-theme-argon'...
error: src refspec 18.06 does not match any
error: failed to push some refs to 'https://github.com/GWen124/luci-theme-argon.git'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TobKed/github-forks-sync-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TobKed/github-forks-sync-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by turbaszek** [comment]
Thanks @GWen124 ! @TobKed does this seems to be related to fix in #9 ?

**Comment by TobKed** [comment]
Thanks @GWen124 and @turbaszek . I made PR with the fix (not related to the tags).

**Comment by GWen124** [comment]
Thanks for your hard work

**Comment by GWen124** [comment]
@TobKed  how to get all branches

**Comment by GWen124** [comment]
> Thanks @GWen124 and @turbaszek . I made PR with the fix (not related to the tags).
Thanks for your hard work
how to get all branches

**Comment by GWen124** [comment]
> Thanks @GWen124 and @turbaszek . I made PR with the fix (not related to the tags).


I mean, how to clone all branches of the same repository at once.

**Comment by TobKed** [comment]
@GWen124 I created seperate issue https://github.com/TobKed/github-forks-sync-action/issues/13 for that. I will work on adding such option.

**Comment by TobKed** [comment]
@GWen124 I merged fix for non-default branch. Let me know if this works for you.
